Re-implement IRC channel history/logs
67P/hyperchannel pull request #266
Opened 2022-01-09 00:44 UTC by raucao

Re-implements the IRC channel history, based on the new public logs meta documents, so we don't have to search for the most recent log files anymore.

2022-01-09 00:58 UTC, raucao commented
CodeClimate broke our repo page, so I cannot see what it's complaining about. Sent them an email about it.

2022-01-09 19:18 UTC, galfert requested changes
Left a comment, the rest looks ok to me.

2022-01-09 19:38 UTC, raucao commented on app/services/coms.js
> +      this.loadLastMessagesFromKosmosArchives(channel, options.isLogged);
Good catch, thanks!

2022-01-10 19:28 UTC, galfert approved these changes
👍

2022-01-10 19:49 UTC, merged